web/src/main/java/com/lantanagroup/nandina/controller/BaseController.java, web/src/main/java/com/lantanagroup/nandina/controller/LocationController.java, web/src/main/java/com/lantanagroup/nandina/controller/ReportController.java
cleaning up a few minor code review changes
=> flint-87 cleaning up a few minor code review changes

query/src/main/java/com/lantanagroup/nandina/query/fhir/r4/cerner/report/Report.java
this is part one of fixing issues with filters not returning correctly. This fixes it so that we are checking all filter results no matter how many filters are passed in. this is using streams.allMatch() so that we compare the result of all the filter returns. They all have to be true for the result to be true which is what we want. This fixes the results so that we only return data when we are supposed to. There still are some issues that I need to debug with some of the results. Pushing this for now though...
=> NAND-159 part 1

api/pom.xml, cli/pom.xml, core/pom.xml, query/pom.xml, query/src/main/java/com/lantanagroup/nandina/query/measure/fhir/r4/PrepareQuery.java, query/src/main/java/com/lantanagroup/nandina/query/pihc/fhir/r4/cerner/PatientData.java, query/src/main/java/com/lantanagroup/nandina/query/pihc/fhir/r4/cerner/scoop/PatientScoop.java, query/src/test/java/PatientScoopTest.java, query/src/test/java/ResourceLoader.java, web/src/main/angular/assets/config.json
NAND-207,
NAND-218,
NAND-231,
and some data loaders to help Dave and Max load resources faster
=> Changes for multiple tickets

query/src/main/java/com/lantanagroup/nandina/query/measure/fhir/r4/PrepareQuery.java, query/src/main/java/com/lantanagroup/nandina/query/scoop/Scoop.java, query/src/test/java/ResourceLoader.java, web/src/main/angular/app/report-body/measure-eval/measure-eval.component.html
NAND-240 adding delete all resources script
=> NAND-240 adding delete all resources script

core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java, nhsn/src/main/java/com/lantanagroup/link/nhsn/LeidosSender.java
Changing configuration so that `sendUrl` is an array of strings and updating LeidosSender to use array
=> NHSNLINK-468

api/src/main/java/com/lantanagroup/link/api/ApiInit.java, core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java, core/src/main/java/com/lantanagroup/link/config/api/ApiMeasureConfig.java, core/src/main/java/com/lantanagroup/link/config/api/ApiReportDefsConfig.java
Retrying each report def bundle for a configurable number of times, waiting a configurable amount of milliseconds in between each retry
=> NHSNLINK-487

api/src/main/java/com/lantanagroup/link/api/ApiApplication.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/application.yml, core/src/main/java/com/lantanagroup/link/config/query/USCoreConfig.java, core/src/main/java/com/lantanagroup/link/query/IQuery.java, query-api/src/main/java/com/lantanagroup/link/query/api/QueryApiApplication.java, query-api/src/main/java/com/lantanagroup/link/query/api/controller/QueryController.java, query/src/main/java/com/lantanagroup/link/query/BaseQuery.java, query/src/main/java/com/lantanagroup/link/query/QueryFactory.java, query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java, query/src/main/java/com/lantanagroup/link/query/uscore/Query.java, query/src/main/java/com/lantanagroup/link/query/uscore/scoop/PatientScoop.java, query/src/main/java/com/lantanagroup/link/query/uscore/scoop/Scoop.java
Making queries to source FHIR server configurable
=> NHSNLINK-496

api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, core/src/main/java/com/lantanagroup/link/Helper.java, web/src/main/angular/app/app.module.ts, web/src/main/angular/app/model/report-patient.ts, web/src/main/angular/app/report/report.component.html, web/src/main/angular/app/report/report.component.ts, web/src/main/angular/app/services/report.service.ts, web/src/main/angular/app/view-line-level/view-line-level.component.html, web/src/main/angular/app/view-line-level/view-line-level.component.ts
Adding modal component that shows patient data for a given report
Adding button to view line-level data
Opening modal window when button is pressed
Stubbing out View/Exclude buttons for each patient (they don't do anything, yet)
=> NHSNLINK-520

web/src/main/angular/app/review/review.component.css, web/src/main/angular/app/review/review.component.html
Modifications to separate filters into its own card above the table. That's basically it.
=> Review UI layout

api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, core/src/main/java/com/lantanagroup/link/IPatientIdProvider.java, core/src/main/java/com/lantanagroup/link/ResourceIdChanger.java, core/src/main/java/com/lantanagroup/link/model/PatientOfInterestModel.java, core/src/main/java/com/lantanagroup/link/query/IQuery.java, nhsn/src/main/java/com/lantanagroup/link/nhsn/StoredListProvider.java, query-api/src/main/java/com/lantanagroup/link/query/api/controller/QueryController.java, query/src/main/java/com/lantanagroup/link/query/uscore/Query.java, query/src/main/java/com/lantanagroup/link/query/uscore/scoop/PatientScoop.java, query/src/test/java/com/lantanagroup/link/query/uscore/QueryTests.java
Allow patient identifier lists that use logical ID instead of identifier
=> NHSNLINK-394

.idea/artifacts/api_war_exploded.xml, .idea/artifacts/query_api_war_exploded.xml, .idea/compiler.xml, .idea/encodings.xml, .idea/modules.xml, Dockerfile.consumer, api/pom.xml, cli/pom.xml, consumer/pom.xml, consumer/src/main/java/com/lantanagroup/link/consumer/api/ConsumerApiApplication.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/FhirServerConfigR4.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/JpaHibernatePropertiesProvider.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/JpaRestfulServer.java, consumer/src/main/resources/application.yml, core/pom.xml, nhsn/pom.xml, pom.xml, query-api/pom.xml, query/pom.xml
Adding "consumer" project that uses HAPI to launch a basic FHIR server. Not a ton of bells and whistles setup by default in it, it's pretty bare bones. Will likely need to add more configurations to it in the future, but is a good starting point for the "consumer" actor.
I suggest not getting lost in some of the weeds of HAPI, but reviewing this from a higher perspective of being aware of the new module in the project and its layout of files/code.
=> THSALINK-4

api/src/main/java/com/lantanagroup/link/api/controller/ReportDefinitionController.java, api/src/test/java/com/lantanagroup/link/api/controller/ReportDefinitionControllerTest.java, core/src/main/java/com/lantanagroup/link/FhirDataProvider.java
I modified ReportDefinitionController.java to use FHIRDataProvider and created a unit test for the modified functionality.
=> Nhsnlink 615

core/src/main/java/com/lantanagroup/link/FhirDataProvider.java, core/src/main/java/com/lantanagroup/link/FhirHelper.java, core/src/test/java/com/lantanagroup/link/FhirHelperTests.java, nhsn/src/main/java/com/lantanagroup/link/nhsn/FHIRSender.java
I updated FhirHelper.java to use FHIRDataProvider and created unit tests for it.
=> Nhsnlink 622

api/src/main/resources/application.yml, core/src/main/java/com/lantanagroup/link/config/query/USCoreConfig.java, query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java, query/src/test/java/com/lantanagroup/link/query/uscore/QueryTests.java
I updated PatientData to find all the references from queried resources and then retrieve the resources from those references and add them to the bundle with no duplicate resources.
=> Nhsnlink 625

.idea/misc.xml, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/application.yml, query/src/main/java/com/lantanagroup/link/query/auth/EpicAuth.java
Extra logging in Epic authentication
Fix issue in report id creation for new reports
Update config to use shortened query
=> Generation fixes

api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/test/java/com/lantanagroup/link/api/controller/ReportGeneratorTests.java
I modified ReportGenerator to retrieve the location url from the response of the transaction of updates on the internal FHIR server for MeasureReports and doc ref, then updated the DocumentReference with that location.
=> Nhsnlink 588

api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/test/java/com/lantanagroup/link/api/controller/ReportGeneratorTests.java
=> Revert "Nhsnlink 588"

api/src/main/java/com/lantanagroup/link/api/controller/ReportDataController.java, api/src/test/java/com/lantanagroup/link/api/controller/ReportDataControllerTest.java
Stubbed out an endpoint that receives CSV data, parses it, and checks its type variable for "bed" or "ventilator".
=> Nhsnlink 685

api/src/main/java/com/lantanagroup/link/api/controller/PatientIdentifierController.java, api/src/test/java/com/lantanagroup/link/api/controller/PatientIdentifierControllerTests.java
Modified the getPatientIdentifierList functions for both XML and JSON to check if the measure fron the Patient List's Identifier is found in NHSNLink or else it throws a 400 Bad Request error.
=> Nhsnlink 573

.idea/compiler.xml, agent/src/main/java/com/lantanagroup/link/agent/controller/AgentController.java, api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, cli/src/main/java/com/lantanagroup/link/cli/QueryCommand.java, core/src/main/java/com/lantanagroup/link/model/QueryResponse.java, core/src/main/java/com/lantanagroup/link/model/ReportContext.java, core/src/main/java/com/lantanagroup/link/query/IQuery.java, query/src/main/java/com/lantanagroup/link/query/uscore/Query.java, query/src/test/java/com/lantanagroup/link/query/uscore/QueryTests.java
Created the QueryResponse class to contain Patient Id and a Patient data bundle, then modified Query.execute, ReportController.getRemotePatientData, ReportController.queryAndStorePatientData, and AgentController.getData to return List<QueryResponse>.  I then modified ReportContext to store a List<QueryResponse> as patientData and modified GenerateResponse to store the List<QueryResponse> generated into ReportContext.
=> Nhsnlink 759

core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
Added evaluationService to ApiConfig.java with a setter and getter.
=> NHSNLINK-698

.idea/artifacts/consumer_war_exploded.xml, api/src/main/java/com/lantanagroup/link/api/ApiApplication.java, api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/main/java/com/lantanagroup/link/api/auth/LinkAuthenticationSuccessHandler.java, api/src/main/java/com/lantanagroup/link/api/controller/BaseController.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, core/src/main/java/com/lantanagroup/link/FhirDataProvider.java, core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
Created a new instance of FhirDataProvider that points to the measure evaluation service base URL to store the measure resources in storeReportBundleResources and modified the FhirDataProvider's constructor to take in a string.
Doing this before 660 hoping it helps prevent things from breaking.
=> Nhsnlink 760

api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java
Added the patientDataBundle from QueryResponse to Paramters for getting the master measure report as "additionalData". Then modified Measure Evaluator to create another instance of FhirDataProvider using EvaluationService to get the measure report.
=> Nhsnlink 660

api/src/main/java/com/lantanagroup/link/api/controller/PatientIdentifierController.java, api/src/test/java/com/lantanagroup/link/api/controller/PatientIdentifierControllerTests.java, core/src/main/java/com/lantanagroup/link/model/CsvEntry.java
Modified PatientIdentifierController and CsvEntry to capture the start and end dates in the CSV Census list.
=> List applicable period

.idea/artifacts/consumer_war_exploded.xml, api/src/main/java/com/lantanagroup/link/api/ApiApplication.java, api/src/main/java/com/lantanagroup/link/api/ApiInit.java, api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java, api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/main/java/com/lantanagroup/link/api/auth/LinkAuthenticationSuccessHandler.java, api/src/main/java/com/lantanagroup/link/api/controller/BaseController.java, api/src/main/java/com/lantanagroup/link/api/controller/PatientIdentifierController.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/fhir/list-applicable-period-end.xml, api/src/main/resources/fhir/list-applicable-period-start.xml, api/src/test/java/com/lantanagroup/link/api/controller/PatientIdentifierControllerTests.java, core/src/main/java/com/lantanagroup/link/Constants.java, core/src/main/java/com/lantanagroup/link/FhirDataProvider.java, core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java, core/src/main/java/com/lantanagroup/link/model/CsvEntry.java, nhsn/src/main/java/com/lantanagroup/link/nhsn/StoredListProvider.java, web/src/main/angular/app/generate/generate.component.html
The epic to use CQF-Ruler to evaluate measures should now be complete and ready to integrate into master branch.
=> Nhsnlink 672

consumer/pom.xml, consumer/src/main/java/com/lantanagroup/link/consumer/api/AuthInterceptor.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/JpaRestfulServer.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/ReportCsvOperationProvider.java, consumer/src/main/java/com/lantanagroup/link/consumer/api/ReportCsvProvider.java, thsa/pom.xml, thsa/src/main/java/com/ainq/fhir/utils/YamlUtils.java, thsa/src/main/java/com/ainq/saner/converters/SanerCSVConverter.java, thsa/src/main/java/com/ainq/saner/converters/csv/AbstractConverter.java, thsa/src/main/java/com/ainq/saner/converters/csv/CSVConversionException.java, thsa/src/main/java/com/ainq/saner/converters/csv/CsvToReportConverter.java, thsa/src/main/java/com/ainq/saner/converters/csv/ReportToCsvConverter.java, thsa/src/main/java/com/ainq/saner/converters/csv/Util.java, thsa/src/main/resources/THSAMasterAggregate.xml
Note that the code added to `thsa` is from `NHSNLINK-694` (and ultimately from [Saner-CSV-Converter](https://github.com/AudaciousInquiry/Saner-CSV-Converter)).  It should not need to be reviewed closely.
=> LINK-874: Transform CSV report submission in consumer and store

api/src/main/java/com/lantanagroup/link/api/ApiApplication.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportDataController.java, api/src/test/java/com/lantanagroup/link/api/controller/ReportDataControllerTest.java, core/src/main/java/com/lantanagroup/link/IDataProcessor.java, core/src/main/java/com/lantanagroup/link/config/thsa/THSAConfig.java, thsa/src/main/java/com/lantanagroup/link/thsa/GenericCSVProcessor.java
Implemented IDataProcessor in GenericDataProcessor to get a measure report from csv data and storing it on the fhir server with inventorydata from the dataMeasureReportId value in THSAConfig as its id.
=> Create CSV processor for CSV data

api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java
Adding logic to de-dup patients directly out of the census and also after querying has occurred and we know if the same patient showed up multiple times with different business identifiers
=> Patient De-Dup

core/src/main/java/com/lantanagroup/link/Helper.java
Added StringUtils.isEmpty checks for helper validator methods.
=> LINK-1048: Add null check for logger helper functions

api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/application.yml, core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
I removed the logic from deleteSentData in ReportControler that immediately deletes data after report submission.
=> Remove logic that deletes data immediately after report generation/submission

cli/src/main/java/com/lantanagroup/link/cli/RefreshPatientListCommand.java, cli/src/main/java/com/lantanagroup/link/cli/RefreshPatientListConfig.java, core/src/main/java/com/lantanagroup/link/config/api/ApiReportDefsUrlConfig.java
…f-Interest lists for each configured Measure
=> LINK-1153_Update_Census_acquisition_functionality_

.idea/misc.xml, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, cli/src/main/java/com/lantanagroup/link/cli/GenerateAndSubmitCommand.java, cli/src/main/java/com/lantanagroup/link/cli/QueryCommand.java, core/src/main/java/com/lantanagroup/link/config/auth/LinkOAuthConfig.java, core/src/main/java/com/lantanagroup/link/csv/MeasureReportToCSV.java, query/src/main/java/com/lantanagroup/link/query/BaseQuery.java, query/src/main/java/com/lantanagroup/link/query/auth/HapiFhirAuthenticationInterceptor.java
Replaced all usages of org.apache.logging.log4j.util.Strings with org.apache.commons.lang3.StringUtils.
=> Change string validation library

core/src/main/java/com/lantanagroup/link/validation/Validator.java, core/src/test/java/com/lantanagroup/link/FhirBundlerTests.java, core/src/test/java/com/lantanagroup/link/validation/ValidatorTests.java
Add unit tests to ensure that validation is working as intended.
For: https://lantana.atlassian.net/browse/LNK-689
=> LNK-689: Validator validation

api/src/main/java/com/lantanagroup/link/api/ApiInit.java, api/src/main/java/com/lantanagroup/link/api/controller/TenantController.java, api/src/main/java/com/lantanagroup/link/api/scheduling/Scheduler.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java, core/src/main/resources/shared-db.sql
SharedService TenantConfig to SQL changes
=> sharedService TenantConfig to SQL

api/src/main/resources/swagger.yml
Hey @seanmcilvenna, 
Here's an initial PR for the initial descriptions of tenant config related settings. One note, listId on line 1296 has a TODO. Any suggestions on how to best describe that field?
Thanks,
Daniel
=> Added some additional descriptions around Tenant config related properties

api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/main/java/com/lantanagroup/link/api/controller/MeasureDefController.java, api/src/main/java/com/lantanagroup/link/api/controller/MeasurePackageController.java, api/src/main/java/com/lantanagroup/link/api/controller/PatientIdentifierController.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, core/src/main/java/com/lantanagroup/link/db/SQLCSHelper.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java, core/src/main/resources/shared-db.sql
Remaining items to convert SharedService.java to use SQL Server in place of Mongo.
=> SharedService SQL Server Conversion

api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java, api/src/main/java/com/lantanagroup/link/api/controller/ApiController.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/application.yml, core/src/main/java/com/lantanagroup/link/Constants.java, core/src/main/java/com/lantanagroup/link/FhirBundler.java, core/src/main/java/com/lantanagroup/link/Helper.java, core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java, core/src/main/java/com/lantanagroup/link/db/model/tenant/Events.java, core/src/main/java/com/lantanagroup/link/model/ApiInfoModel.java, core/src/main/java/com/lantanagroup/link/validation/Validator.java, core/src/test/java/com/lantanagroup/link/FhirBundlerTests.java
Per chagnes to nhsn-measures IG, adding a Device that represents the submitting device (i.e. NHSNLink) to the submission bundle. The Device includes version information based on the build.yml file that gets added to src/main/resources during the devops build processes.
When validating, attaching the Device from the submission bundle to the OperationOutcome validation results for traceability.
=> Adding submitting-device resource to submission bundle

core/src/test/java/com/lantanagroup/link/validation/ValidatorTests.java, core/src/test/resources/large-submission-example2.json
Create Unit Tests to ensure the Validator is capturing the expected issues with bundles against various proifiles.
=> LINK_740_ValidatorUnitTests

core/src/main/java/com/lantanagroup/link/ResourceIdChanger.java, core/src/test/java/com/lantanagroup/link/ResourceIdChangerTests.java, core/src/test/resources/duplicate-observation-bundle.json
Implement a Fix to the ResourceIdChanger normalization, with a corresponding Unit Test, to validate that multiple resources with the same Id do not cause the normalization to fail and end processing.
=> ResourceIdChanger Fixes

api/src/main/resources/logback.xml, core/pom.xml, core/src/main/resources/shared-db.sql, pom.xml
Updated shared-db.sql to create the logback sql server tables (three of them)
Logback configuration changes to use DBAppender to store logs in the three tables
=> Store logs in DB

api/src/main/java/com/lantanagroup/link/api/controller/MetricController.java, core/src/main/java/com/lantanagroup/link/Constants.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java, core/src/main/java/com/lantanagroup/link/model/EvaluationMetric.java, core/src/main/java/com/lantanagroup/link/model/MetricsReportResponse.java, core/src/main/java/com/lantanagroup/link/model/PatientsQueriedMetric.java, core/src/main/java/com/lantanagroup/link/model/PatientsReportedMetric.java, core/src/main/java/com/lantanagroup/link/model/QueryTimeMetric.java, core/src/main/java/com/lantanagroup/link/model/ValidationMetric.java
Added a new metrics rest controller along with methods to calculate the various metrics needed for reporting.
=> LNK-1360: Reporting metrics rest controller

api/src/main/java/com/lantanagroup/link/api/controller/QAController.java, core/src/main/java/com/lantanagroup/link/db/TenantService.java, core/src/main/java/com/lantanagroup/link/db/repositories/PatientListRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/ReportRepository.java
Add to delete all reports and patient lists when deleting by report id or patient list id.
=> Addl functionality for deletes

api/src/main/java/com/lantanagroup/link/api/controller/PatientIdentifierController.java, api/src/main/java/com/lantanagroup/link/api/controller/TenantController.java, core/src/main/java/com/lantanagroup/link/ReportingPeriodCalculator.java, core/src/main/java/com/lantanagroup/link/db/model/tenant/Tenant.java
LNK-1448 - Make Census Acquisition TimeZone aware
=> LNK-1448 - Make Census Acquisition TimeZone aware

api/src/main/java/com/lantanagroup/link/api/controller/GlobalReportController.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java
Fixed issue where the measureIds where not be added to the SQL query for getting reports.
Added additional functionality in the getReports endpoint to use the following parameters:
- measureIds
- count
- page
=> LNK-1554: Ability to search for reports

api/src/main/java/com/lantanagroup/link/api/controller/GlobalReportController.java
Made a small fix to prevent reports getting excluded when no measure ids where submitted.
=> Fix for the measure id filter for global report searching.

api/src/main/java/com/lantanagroup/link/api/controller/GlobalReportController.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java
Changed the timestamp format to `MM/dd/yyyy HH:mm:ss`
=> Metric timestamp fix

api/src/main/resources/swagger.yml
Updated the swagger spec for Report to match the GlobalReportResponse model in the api.
=> Update the swagger spec GlobalReportResponse to match the API model

web/src/app/pages/activities/activities.component.html, web/src/app/pages/activities/activities.component.ts, web/src/app/pages/facilities/facilities.component.html, web/src/app/pages/facilities/facilities.component.ts, web/src/app/shared/interfaces/table.model.ts, web/src/app/shared/table/table.component.html, web/src/app/shared/table/table.component.scss, web/src/app/shared/table/table.component.ts, web/src/scss/base/_form.scss
* Updating the table component to be more self-sufficient
* enabling search, and customizing to match designs
* updated activities and facilities views
=> adding custom search bar to data tables

web/src/app/pages/activities/activities.component.ts, web/src/app/pages/dashboard/dashboard.component.ts
- removed unused comments to re-trigger deployment.
=> force-commit-ui-changes-to-trigger-deployment

web/src/app/app.component.html, web/src/app/pages/activities/activities.component.ts, web/src/app/pages/activities/bundle/bundle.component.html, web/src/app/pages/activities/bundle/bundle.component.ts, web/src/app/pages/facilities/facilities.component.ts, web/src/app/pages/facilities/facility/facility.component.html, web/src/app/shared/accordion/accordion.component.scss, web/src/app/shared/hero/hero.component.html, web/src/app/shared/hero/hero.component.ts, web/src/main.ts, web/src/scss/base/_globals.scss
Layout of basic individual bundle page
=> demoing out bundle pages

.idea/misc.xml, core/src/main/java/com/lantanagroup/link/FhirBundlerEntrySorter.java, core/src/test/java/com/lantanagroup/link/FhirBundlerTests.java, core/src/test/java/com/lantanagroup/link/TestHelper.java, core/src/test/java/com/lantanagroup/link/validation/ValidatorTests.java
Temporary unit test against a large bundle came down from 800ms to 200ms.
=> LNK-1861 Performance improvements to sorting for RC_0.3.2

web/src/app/pages/facilities/facilities.component.ts, web/src/app/pages/facilities/facility/facility.component.html, web/src/app/pages/facilities/facility/facility.component.ts, web/src/app/shared/interfaces/tenant.model.ts, web/src/services/api/facilities/facilities-api.service.ts
implementing an ajax call for the facilities table, api call only returns current page
=> Feature/slnl 14  facilities

api/src/main/java/com/lantanagroup/link/api/ApiInit.java, api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java, api/src/main/java/com/lantanagroup/link/api/controller/DataController.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/swagger.yml, core/src/main/java/com/lantanagroup/link/db/TenantService.java, core/src/main/java/com/lantanagroup/link/db/mappers/AggregateMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/BaseMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/BulkStatusMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/BulkStatusResultMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/ConceptMapMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/DataTraceMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/PatientDataMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/PatientListMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/PatientMeasureReportMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/QueryMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/ReportMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/ValidationResultCategoryMapper.java, core/src/main/java/com/lantanagroup/link/db/mappers/ValidationResultMapper.java, core/src/main/java/com/lantanagroup/link/db/repositories/DataTraceRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/PatientDataRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/QueryRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/ValidationCategoryRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/ValidationRepository.java, core/src/main/resources/tenant-db.sql, core/src/main/resources/terminology/CodeSystem-v3-ucum.json, core/src/main/resources/terminology/deqm/StructureDefinition-extension-criteriaReference.json, core/src/main/resources/terminology/uscore/CodeSystem-medicationrequest-category.json, core/src/main/resources/terminology/uscore/StructureDefinition-us-core-genderIdentity.json, query/src/main/java/com/lantanagroup/link/query/uscore/PatientScoop.java
@seanmcilvenna, guessing this will need your approval, as I'm unable to push directly to `rc_0.3.2`.
=> Push `development` to `rc_0.3.2`

web/src/app/pages/activities/activities.component.ts
- formatting a date per Spyglass feedback
=> formatting a date on the activities table

web/src/app/helpers/ReportHelper.ts, web/src/app/pages/activities/bundle/bundle.component.html, web/src/app/pages/system-performance/system-performance.component.html, web/src/app/pages/system-performance/system-performance.component.scss, web/src/app/pages/system-performance/system-performance.component.ts, web/src/app/shared/link/link.component.scss, web/src/app/shared/navbar/navbar.component.scss
- adding a line break to dummy data
- visually centering external link icon
- changing press vs current page color for nav
- increasing card spacing on system performance page
- tightening up a margin on dummy measure data
=> final Spyglass feedback

query/src/main/java/com/lantanagroup/link/query/uscore/BulkQuery.java
Fix error related to no auth for a tenant in bulk
=> LNK 1879 - Unable to Initiate Bulk Data

core/src/main/java/com/lantanagroup/link/FhirBundlerEntrySorter.java
From yesterday's discussion on #arch.
=> Ensure bundle sorting retains all entries

web/src/app/pages/activities/activities.component.ts, web/src/app/pages/dashboard/dashboard.component.ts, web/src/app/pages/facilities/facility/facility.component.html, web/src/app/pages/login/login.component.html, web/src/app/pages/login/login.component.scss, web/src/app/pages/login/login.component.ts, web/src/app/shared/form-update-facility/form-update-facility.component.html, web/src/app/shared/form-update-facility/form-update-facility.component.ts, web/src/app/shared/header/header.component.ts, web/src/app/shared/interfaces/tenant.model.ts, web/src/callback/callback.component.ts, web/src/environments/environment.dev.ts, web/src/environments/environment.prod.ts, web/src/environments/environment.test.ts, web/src/environments/environment.ts, web/src/services/api/data.service.ts, web/src/services/api/globals/globals-api.service.ts, web/src/services/auth/auth.service.ts
- accidentally overwriting a variable and mapping was happening incorrectly.
=> fixing a normalizing mapping

web/src/app/app.component.ts
- handing off to client, removing bugherd script used for Spyglass QA
=> removing bugherd script

.idea/.gitignore, web/src/app/app.config.ts, web/src/app/pages/profile/profile.component.html, web/src/app/pages/profile/profile.component.ts, web/src/assets/app.config.json, web/src/main.ts, web/src/services/api/data.service.ts, web/src/services/app.config.ts, web/src/services/auth/auth.service.ts
For authentication and the base url of the API
To customize per each environment, need to overwrite (or mount) a custom `app.config.json` file to the deployed assets directory within the pod/container.
Default configuration points to DEV for the API.
=> Creating app config that can be altered in each deployed environment

core/src/main/java/com/lantanagroup/link/db/SharedService.java, core/src/main/java/com/lantanagroup/link/model/TenantSummary.java, core/src/main/java/com/lantanagroup/link/model/TenantSummaryMeasure.java
Add totalPatients and includedPatients to TenantSummaryReport.
=> LNK-1847 Add totalPatients and includedPatients

api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java, api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java, api/src/main/resources/swagger.yml, core/src/main/java/com/lantanagroup/link/db/SQLUtils.java, core/src/main/java/com/lantanagroup/link/db/SharedService.java, core/src/main/java/com/lantanagroup/link/db/TenantService.java, core/src/main/resources/insights-shared.sql, core/src/main/resources/insights-tenant.sql, core/src/main/resources/insights.css
Bring in changes from LNK-2263 and LNK-2298 to the v0.4.1 release
=> LNK-2322: Bring in latest changes from development branch to rc_0.4.1 branch

api/pom.xml, core/pom.xml, nhsn/pom.xml, pom.xml, query/pom.xml
PR to cover pom.xml files being updated with the new version number.
=> Bump versions in pom.xml files to 0.4.2-SNAPSHOT

core/src/main/java/com/lantanagroup/link/db/TenantService.java, core/src/main/java/com/lantanagroup/link/db/repositories/ValidationCategoryRepository.java, core/src/main/java/com/lantanagroup/link/db/repositories/ValidationRepository.java
- Replace `WHERE ... IN (SELECT ...)` with `JOIN`.
- Remove explicit `validationResultCategory` deletion.
=> Tune `DELETE` query

api/pom.xml, core/pom.xml, nhsn/pom.xml, pom.xml, query/pom.xml
@smailliwcs I know it's late in the game, and probably doesn't matter that much, but I removed the _-SNAPSHOT_ from the version in the RC branch since it's not really the right convention for this use case. Let me know if that's ok with you, though.
=> LNK-2913 - Up-rev to version 0.4.3

api/pom.xml, core/pom.xml, nhsn/pom.xml, pom.xml, query/pom.xml
Merge rc_0.4.4 branch contents to master, where it will be tagged as v0.4.4
=> Merge rc_0.4.4 branch to master

api/pom.xml, core/pom.xml, nhsn/pom.xml, pom.xml, query/pom.xml
=> LNK-3922: Bump version from 0.5.4-SNAPSHOT to 0.5.4 in POM files
