lantanagroup/link

- query/src/main/java/com/lantanagroup/nandina/query/fhir/r4/cerner/PatientData.java
Changing queries to use "patient" parameter instead of "subject". "subject" is not supported by Cerner's FHIR API.
> Changes required for cerner sandbox

- api/src/main/java/com/lantanagroup/nandina/FhirHelper.java
- api/src/main/java/com/lantanagroup/nandina/controller/LocationController.java
- api/src/main/java/com/lantanagroup/nandina/controller/ReportController.java
- api/src/main/resources/config.json
- core/src/main/java/com/lantanagroup/nandina/JsonProperties.java
- query/src/main/java/com/lantanagroup/nandina/query/fhir/r4/saner/Constants.java
- query/src/main/java/com/lantanagroup/nandina/query/fhir/r4/saner/FormQuery.java
- query/src/main/java/com/lantanagroup/nandina/query/fhir/r4/saner/PrepareQuery.java
- web/src/main/angular/app/questionnaire/questionnaire.component.html
Adding queryCriteria to configuration so that admins can indicate additional criteria to be added to FHIR server queries
Updating the SANER queries so that it uses multiple code systems to find data Nandina's interested in, as well as to update the fields' codes based on updates to the SANER IG
Setting field in UI to bind to correct answer
Changing AuditEvent creation to set the type isntead of subtype.
Making "type" based on pre-defined enum of options.
Fixing issue with export attempting to store AuditEvents in the query server, instead of the storage server.
Adding in TODO for filling in the "source" of an audit event.
> Connectathon

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- core/src/main/java/com/lantanagroup/link/FhirHelper.java
- core/src/main/java/com/lantanagroup/link/model/PatientReportModel.java
- web/src/main/angular/app/model/report-patient.ts
- web/src/main/angular/app/view-line-level/view-line-level.component.html
- web/src/main/angular/app/view-line-level/view-line-level.component.ts
Changing display of patient name to be "last, first" as a single column instead of two separate first+last columns
Re-using `FhirHelper.getName()` from ReportController. Uses Patient.name.text by default, if provided, otherwise uses Patient.name.family + Patient.name.given.
> Patient name improvement

- nhsn/src/main/java/com/lantanagroup/link/nhsn/FHIRSender.java
Modified FHIRSender to check the Id of bundle entries to find each entry's base url, resource type, and resource id and assign them all together as their respective entry's full url.
> NHSNLink-739

- api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java
- core/src/main/java/com/lantanagroup/link/Constants.java
Checked to see if ApiConfig.terminologyService and ApiConfig.evaluationService are the same in MeasureEvaluator, if not then created a new endpoint set as active with the Address as the same as the ApiConfig.terminologyService and a connectionType with "http://terminology.hl7.org/CodeSystem/endpoint-connection-type" as its system and "hl7-fhir-rest" as its code. This endpoint was then added as a parameter for getting the measure report.
> Send configured terminology service to CQF-Ruler during $evaluate-measure

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- web/src/main/angular/app/report/report.component.html
- web/src/main/angular/app/report/report.component.ts
I added logic to the UI so that it disables the discard button if the report version is greater than or equal to 1.0 and I modified the api to check for the same condition in ReportController.deleteReport() and throw a 400 bad request in such a case.
> Don't allow discarding reports after submission

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- core/src/main/java/com/lantanagroup/link/GenericSender.java
- core/src/main/java/com/lantanagroup/link/IReportSender.java
- nhsn/src/main/java/com/lantanagroup/link/nhsn/FHIRSender.java
- nhsn/src/main/java/com/lantanagroup/link/nhsn/JSONSender.java
- thsa/src/main/java/com/lantanagroup/link/thsa/CSVSender.java
Created functionality to retrieve the patient census list from the submission bundle that was retrieved from the sent location that was added to the doc reference during the last submission. The census list is then added to the dev server and the report context where it is used to populate a list of patients of interest instead of looking them up from the server.
> Retrieve census from submission server when re-generating

- api/src/main/java/com/lantanagroup/link/api/controller/ReportDataController.java
- core/src/main/java/com/lantanagroup/link/IDataProcessor.java
- core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
Added the dataProcessor and dataMeasureReportId properties to ApiConfig and created an interface IDataProcessor in core with a process method. Then I added a check for if the data processor for csv exists based on the configuration in ReportDataController.retrieveCSVData(), if not then it respondes with a 400 Bad Request error. Finally I added  IDataProcessor.process() to ReportDataController with process() being static for now until  IDataProcessor is implemented in LINK-865.
> Configuration to execute interface class for CSV processing

- api/src/main/java/com/lantanagroup/link/api/ApiInit.java
- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- api/src/main/resources/application.yml
- core/src/main/java/com/lantanagroup/link/FhirHelper.java
- core/src/main/java/com/lantanagroup/link/config/query/QueryConfig.java
- core/src/main/java/com/lantanagroup/link/config/query/USCoreConfig.java
- query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java
- query/src/main/java/com/lantanagroup/link/query/uscore/scoop/PatientScoop.java
- query/src/test/java/com/lantanagroup/link/query/uscore/QueryTests.java
Created a USCoreConfig class and moved over parallelPatients, patientResourceTypes, otherResourceTypes to it from QueryConfig and modified the classes that use these values to get them from USCoreConfig instead.
> Refactor properties into USCoreConfig

- consumer/src/main/java/com/lantanagroup/link/consumer/api/JpaRestfulServer.java
- consumer/src/main/java/com/lantanagroup/link/consumer/api/ReportCsvOperationProvider.java
Addresses a suggestion on the previous PR.  We should *preload* the THSA summary measure, rather than falling back to a Java resource if the measure isn't found.
> LINK-874: Transform CSV report submission in consumer and store

- api/src/main/java/com/lantanagroup/link/api/ApiSecurityConfig.java
- api/src/main/java/com/lantanagroup/link/api/auth/PreAuthTokenHeaderFilter.java
- core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
Added check-ip-address configuration option for ApiConfig. By default, it is set to true. To disable it add check-ip-address: false in the config file.
> LINK-1067: Make IP checking for JWT conditional based on configuration

- api/src/main/java/com/lantanagroup/link/api/auth/LinkAuthenticationSuccessHandler.java
Added null checks to isSamePractitioner in LinkAuthenticationSuccessHandler when comparing the practitioner dynamically generated from the JWT to a previously stored practitioner for the practitioner's given name, family name, and email.
> Practitioner lookup fails if name/email missing

- core/src/main/java/com/lantanagroup/link/config/api/ApiConfig.java
Added tenantID to ApiConfig and application-dev.yml
> NHSNLink - Create a config property under api that represents the tenant ID for the facility

- core/src/main/java/com/lantanagroup/link/config/query/USCoreQueryParametersResourceConfig.java
- core/src/main/java/com/lantanagroup/link/config/query/USCoreQueryParametersResourceParameterConfig.java
- nhsn/src/main/java/com/lantanagroup/link/nhsn/PatientDataResourceFilter.java
- query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java
- query/src/test/java/com/lantanagroup/link/query/uscore/PatientDataTests.java
- config query params can apply to more resources than just Observation
- can indicate in config if a param with multiple values should be treated as a single comma-separated query param or separate query params
- can create variable substitutions in the param values for `${periodStart}` and `${periodEnd}` (may expand this out further in future)
> Making query params more flexible via config

- core/src/main/java/com/lantanagroup/link/GenericSender.java
- core/src/main/java/com/lantanagroup/link/config/sender/FileSystemSenderConfig.java
- nhsn/src/main/java/com/lantanagroup/link/nhsn/FileSystemSender.java
- nhsn/src/test/java/com/lantanagroup/link/nhsn/FileSystemSenderTests.java
- nhsn/src/test/java/com/lantanagroup/link/nhsn/GenericSenderTests.java
- Config allows setting path, format (JSON vs. XML) and whether or not it should be pretty-formatted
- Defaults to JSON format if not specified
- Defaults to a temporary directory if not specified
- Uses datetime stamp for file name
- Path must exist to store the submission in
Example config:
```
sender:
file:
path: c:\data\submission
pretty: false
format: JSON
```
> Adding ability to submit reports to a file system for testing/debugging purposes

- query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java
- query/src/test/java/com/lantanagroup/link/query/uscore/PatientDataTests.java
- If "Encounter" resource type is in the data requirements, search for it first
- Build a list of encounter references that can be used later
- Replace ${encounter} token as a separate query string for each encounter
Example/suggested config:
```
query-parameters:
nhsnglycemiccontrolhypoglycemicinitialpopulation:   # Measure.identifier.value
- resourceType: Observation
parameters:
- name: category
single-param: true
values:
- laboratory
- name: date
values:
- 'ge${lookBackStart}'
- 'le${periodEnd}'
- resourceType: ServiceRequest
parameters:
- name: date
values:
- 'ge${lookBackStart}'
- 'le${periodEnd}'
- name: encounter
values:
- '${encounter}'
- resourceType: MedicationRequest
parameters:
- name: date
values:
- 'ge${lookBackStart}'
- 'le${periodEnd}'
- name: encounter
values:
- …
```
> Search for encounters first to support ${encounter} filter in queries

- api/src/main/java/com/lantanagroup/link/api/MeasureEvaluator.java
- api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java
- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- core/src/main/java/com/lantanagroup/link/nhsn/FixResourceId.java
To ideally increase performance and spread the persistence out over time, rather than all at once as a single bundle.
> Persisting individual measure reports immediately after they are evaluated

- api/src/main/resources/swagger.yml
- core/src/main/java/com/lantanagroup/link/FhirScanner.java
- core/src/main/java/com/lantanagroup/link/PeriodDateFixer.java
- core/src/main/java/com/lantanagroup/link/events/FixPeriodDates.java
- core/src/test/java/com/lantanagroup/link/PeriodDateFixerTests.java
Added logic to fix the dates on the encounter periords, primarily when a start date is missing a time component. The code will construct every start/end date in a way that ensure thats a proper time is added if not present.
> Period Date Fix

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- api/src/main/java/com/lantanagroup/link/api/controller/ValidationController.java
- api/src/main/resources/application.yml
- api/src/main/resources/swagger.yml
- core/src/main/java/com/lantanagroup/link/FhirBundler.java
- core/src/main/java/com/lantanagroup/link/Helper.java
- nhsn/src/main/java/com/lantanagroup/link/nhsn/FileSystemSender.java
* Defaulting file sender path to temp directory
* Fixed bug in resolving variables in the sending path. `replaceAll` uses regex in the replacing value, which caused problems.
* Removing logic to clean profiles from resources and adding explicit profile assertions. This is now being handled by the results of the CQF-Ruler (as part of the CQL logic).
* Adding warning statement in logs when resources exist in the bundle without profile assertions, which would cause them not to be validated.
* Moving `expandEnVars` to helper class so that it may be re-used by other classes in the future
* Refactoring validation operations into its own controller and route
* Adding summary operations to provide simple summarization of validation issues
> Fixes to bundling and validation

- core/src/main/java/com/lantanagroup/link/spring/ErrorInfo.java
- core/src/main/java/com/lantanagroup/link/spring/YamlMessageConverter.java
* When HttpMessageNotReadableException is thrown, pass the message from the exception to the user so that they know what went wrong
* Ignoring properties that don't exist from YAML deserialization
> LNK-1198 Provide information to user when requests result in deserialization exception

- core/src/main/java/com/lantanagroup/link/db/BulkStatusService.java
- core/src/main/resources/tenant-db.sql
Remove the concept of the TenantId form the BullkStatus db objects and calls, and tenant-db.sql script.
> BulkStatus - Remove TenantId

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
- core/src/main/java/com/lantanagroup/link/events/CopyLocationIdentifierToType.java
- core/src/main/java/com/lantanagroup/link/model/ReportContext.java
- query/src/main/java/com/lantanagroup/link/query/uscore/PatientData.java
In some cases, we may only need an initial query/evaluate phase, without a subsequent supplemental phase.  This commit updates `ReportController` to recognize such a case, suppress the supplemental phase, and skip straight to aggregation.
> LNK-1406: Change Query Plan configuration to skip supplemental data check when specified

- core/src/main/java/com/lantanagroup/link/FhirBundler.java
`Attachment.setData` already takes care of Base64-encoding the supplied byte array.
> Fix query plan encoding

- core/src/main/java/com/lantanagroup/link/db/SharedService.java
Changed the timestamp format to `MM/dd/yyyy HH:mm:ss`
> Fixed issue with timestamp format when saving metrics.

- web/src/app/shared/card/card.component.scss
referencing the wrong color variable on a dashboard card
> fixing a gray

- core/src/main/java/com/lantanagroup/link/db/SharedService.java
Updated the `generatedTime` and `submittedTime` fields to return the timestamp rather than just the date.
> LNK-1845:  Report API to return precise datetime for generatedTime and submittedTime

- query/src/main/java/com/lantanagroup/link/query/uscore/BulkQuery.java
- Use unqualified versionless ID as `reference`.
- Use identifier (if present) as `identifier`.
> Fix POI creation in bulk acquisition

- api/src/main/java/com/lantanagroup/link/api/controller/TenantController.java
- api/src/main/resources/swagger.yml
- core/src/main/java/com/lantanagroup/link/db/model/tenant/Tenant.java
- core/src/main/java/com/lantanagroup/link/db/model/tenant/TenantVendors.java
- core/src/main/java/com/lantanagroup/link/model/SearchTenantResponse.java
Ran local tests to PUT/GET existing tenants with "vendor", and ensured that "otherVendor" is only allowed when "vendor" is "Other".
> LNK-1854 Added "vendor" and "otherVendor" to tenant config to support the UI

- core/src/main/java/com/lantanagroup/link/validation/Validator.java
Uses resource ID instead of ".ofType(ResourceType)"
Per request from Dave and other FHIR Analysts, to make it easier to work with validation results
> LNK-1809 Improvements to issue FHIRPath expressions

- pom.xml
Fixes an error that occurs when pretty-printing any FHIR resource to JSON.  The root cause is a dependency conflict between Spring Boot 3.2.0 and HAPI 7.0.0.  See HAPI issue #5736:
https://github.com/hapifhir/hapi-fhir/issues/5736
> Update Jackson to 2.16.1

- .idea/.gitignore
- api/src/main/java/com/lantanagroup/link/api/controller/ValidationController.java
- api/src/main/resources/swagger.yml
- core/pom.xml
- core/src/main/java/com/lantanagroup/link/model/ValidationCategoriesAndResults.java
- core/src/main/java/com/lantanagroup/link/model/ValidationResultResponse.java
... together in a single request/response/file where an .XSLT *could* be used to convert it into an .html file that can be shared with stakeholders (something similar is already occuring, but with "valview" python scripts that I'd like to deprecate the use of.
> New endpoint to get both categories and results together

- api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
Update `ReportController.generateResponse` to require acquisition of a tenant-specific lock.
> LNK-2177: MVP: Update NHSNLink code to prevent regeneration of a report for a site if one is already in progress

- api/pom.xml
- core/pom.xml
- nhsn/pom.xml
- pom.xml
- query/pom.xml
@sdmcgeown, FYI, this bumps the versions in our POMs ... something I neglected to do in preparation for the 0.4.0 RC.  I think we'd ideally use the [Maven Release Plugin](https://maven.apache.org/maven-release/maven-release-plugin/) for this sort of thing, but thus far we've done it in a more ad hoc fashion.
Separate PR incoming for the `development` branch, which will be bumped to `0.4.1-SNAPSHOT`.
> Bump `rc_0.4.0` version

- core/src/main/java/com/lantanagroup/link/sender/FileSystemSender.java
`Files.move` is only appropriate for empty directories.  Use `FileUtils.moveDirectory` (Apache Commons) instead.
> Fix folder-based submission bug

- api/src/main/java/com/lantanagroup/link/api/ApiApplication.java
`ApiApplication.main` isn't invoked when running in a servlet container, which impacts our Docker images.  Move cache initialization to `apiInit` to ensure it occurs regardless of deployment method.
> Move cache initialization to `apiInit`
